### ISSUE TITLE
Suggested enhancement - GitFileHistoryProvider and GitFileHistory optionally follow resource renames

### ISSUE THREAD

**Issue by sroughley** [loetscher/egit#1]
It would be useful if `GitFileHistoryProvider` and `GitFileHistory` could optionally follow renames.  This would allow using org.eclipse.team.core API features to follow a full history, rather than just the history since the last rename.  The functionality to follow renames in the history exists within the history ui.

This additional functionality could be added I believe in a non-breaking manner by either adding a `boolean` flag in the two classes for this behaviour, which would default to the current behaviour unless a call to a setter had been made, e.g.

```
GitFileHistoryProvider hp = ...
hp.setFollowRenames(true);
```
Or altenatively by adding an additional flag to the current flags (only 0, 1 and 2 are defined in `IFileHistoryProvider`)

**Comment by loetscher** [comment]
This repo is a fork from the original egit repo (https://git.eclipse.org/r/plugins/gitiles/egit/egit). The fork will not be actively maintained.
You may want to open the enhancement request on the original project: https://www.eclipse.org/egit/
